sudo: required

language: go

services:
  - docker

before_install:
  - docker pull golang
  - docker run golang /bin/sh -c 'echo docker'
  - docker ps -a

script:
  - docker run -v $(pwd):/go golang make
  - docker run -v $(pwd):/go golang id
  - docker run -v $(pwd):/go golang env
  - ls -la
  - hostname
  - env
  - id
